# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clock', '0002_auto_20151215_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=25)),
            ],
        ),
    ]
